version: "3"
services:
  fp-backapp:
    build:
      context: docker/app
      dockerfile: Dockerfile
    ports:
     - "8090:80"
    volumes:
     - .:/code
     - ./docker/app/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - fp-php:php
      - fp-db:db
      - fp-redis:redis
#      - fp-mongo:mongo
    extra_hosts:
      - fp:127.0.0.1
    depends_on:
      - fp-php
      - fp-db
      - fp-redis
  fp-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
     - "9000:9000"
    volumes:
     - ./src/app:/code
    links:
      - fp-db:db
      - fp-redis:redis
#      - fp-mongo:mongo
    depends_on:
      - fp-db
      - fp-redis
#      - fp-mongo
  fp-db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'devel_db'
      MYSQL_USER: 'devel'
      MYSQL_PASSWORD: 'devel'
    volumes:
      - './src/app/data/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql'
      - './src/app/data/sql/dump_data.sql:/docker-entrypoint-initdb.d/dump_data.sql'
      - './docker/db/conf:/etc/mysql/conf.d'
      - './docker/data/db:/var/lib/mysql'
      - './docker/log/db:/var/log/mysql'
  fp-redis:
    image: 'redis:4'
    restart: always
    ports:
     - "6378:6379"
    volumes:
      - './docker/data/redis:/data'
  fp-adminer:
    image: adminer
    restart: always
    links:
      - fp-db:db
    ports:
      - 8091:8080
