version: "3"
services:
  app:
    image: nginx
    working_dir: /usr/local/app
    ports:
    - "8090:80"
    volumes:
    - .:/usr/local/app
    - ./docker/app/site.conf:/etc/nginx/conf.d/default.conf
    links:
    - php:php
    - db:db
    - redis:redis
    - mongo:mongo
    depends_on:
    - php
    - db
    - redis
    - mongo
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
    - "9000:9000"
    volumes:
    - .:/usr/local/app
    links:
    - db:db
    - redis:redis
    - mongo:mongo
    depends_on:
    - db
    - redis
    - mongo
  db:
image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - './data/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql'
    - './data/sql/dump_data.sql:/docker-entrypoint-initdb.d/dump_data.sql'
    - './docker/db/conf:/etc/mysql/conf.d'
    - './docker/data/db:/var/lib/mysql'
    - './docker/log/db:/var/log/mysql'
  mongo:
    image: mongo
#    build:
#      context: ./docker/mongo
#      dockerfile: Dockerfile
    restart: always
    environment:
#    - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
#    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
    - './docker/data/mongo/db:/data/db'
    - './docker/data/mongo/configdb:/data/configdb'
    ports:
    - "27018:27017"
  mongo-express:
    image: mongo-express
    hostname: mongo-express
    restart: always
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
#    - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
    - ME_CONFIG_MONGODB_ADMIN_USERNAME=${MONGO_ROOT_USER}
    - ME_CONFIG_MONGODB_ADMIN_PASSWORD=${MONGO_ROOT_PASSWORD}
    - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
    - mongo
    links:
    - mongo:mongo
    ports:
    - "8096:8081"
  redis:
    image: 'redis:latest'
    restart: always
    hostname: redis
    ports:
    - "6378:6379"
    volumes:
    - './docker/data/redis:/data'
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    hostname: redis-commander
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8095:8081"
  adminer:
    image: adminer
    hostname: adminer
    restart: always
    links:
    - db:db
    ports:
    - 8091:8080
