version: "3"
services:
  fp-app1:
    build:
      context: ./docker/app1
      dockerfile: Dockerfile
    ports:
     - "8090:80"
    volumes:
     - ./src/app1/public:/code
     - ./docker/app1/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - fp-php:php
      - fp-db:db
      - fp-redis:redis
    extra_hosts:
      - fp:127.0.0.1
    depends_on:
      - fp-php
      - fp-db
      - fp-redis
    networks:
      front_net:
        ipv4_address: 172.16.238.10
      back_net:
        ipv4_address: 172.16.239.10
  fp-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
     - "9000:9000"
    volumes:
     - ./src/app1/public:/code
    links:
      - fp-db:db
      - fp-redis:redis
    depends_on:
      - fp-db
      - fp-redis
    networks:
      back_net:
        ipv4_address: 172.16.239.11
  fp-db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    image: fp/db:latest
    container_name: fp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'devel'
      MYSQL_USER: 'devel'
      MYSQL_PASSWORD: 'devel'
    volumes:
      - './src/data/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql'
      - './src/data/sql/dump_data.sql:/docker-entrypoint-initdb.d/dump_data.sql'
      - './docker/db/conf:/etc/mysql/conf.d'
      - './docker/data/db:/var/lib/mysql'
      - './docker/log/db:/var/log/mysql'
    networks:
      back_net:
        ipv4_address: 172.16.239.12
  fp-redis:
    image: 'redis:4'
    container_name: fp_redis
    restart: always
    volumes:
      - './docker/data/redis:/data'
    networks:
      back_net:
        ipv4_address: 172.16.239.13
  fp-app2:
    build:
      context: ./docker/app2
      dockerfile: Dockerfile
    ports:
     - "8092:80"
    volumes:
     - ./src/app2:/code
     - ./docker/app2/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - fp-php:php
      - fp-db:db
      - fp-redis:redis
    extra_hosts:
      - fp:127.0.0.1
    depends_on:
      - fp-php
      - fp-db
      - fp-redis
    networks:
      front_net:
        ipv4_address: 172.16.238.15
  fp-adminer:
    image: adminer:fastcgi
    container_name: fp_adminer
    restart: always
    links:
      - fp-php:php
      - fp-db:db
    ports:
      - 8091:8080
    networks:
      back_net:
        ipv4_address: 172.16.239.14

networks:
  front_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  back_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
